// Mocks generated by Mockito 5.4.6 from annotations
// in from_fed_to_chain_app/test/features/content/domain/use_cases/load_episodes_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:from_fed_to_chain_app/features/content/data/episode_repository.dart'
    as _i2;
import 'package:from_fed_to_chain_app/features/content/models/audio_file.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EpisodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeRepository extends _i1.Mock implements _i2.EpisodeRepository {
  MockEpisodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AudioFile>> loadAllEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #loadAllEpisodes,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AudioFile>>.value(<_i4.AudioFile>[]),
      ) as _i3.Future<List<_i4.AudioFile>>);

  @override
  _i3.Future<List<_i4.AudioFile>> loadEpisodesForLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEpisodesForLanguage,
          [language],
        ),
        returnValue: _i3.Future<List<_i4.AudioFile>>.value(<_i4.AudioFile>[]),
      ) as _i3.Future<List<_i4.AudioFile>>);

  @override
  _i3.Future<List<_i4.AudioFile>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEpisodes,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.AudioFile>>.value(<_i4.AudioFile>[]),
      ) as _i3.Future<List<_i4.AudioFile>>);

  @override
  _i3.Future<_i4.AudioFile?> getEpisodeById(
    String? contentId, {
    String? preferredLanguage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodeById,
          [contentId],
          {#preferredLanguage: preferredLanguage},
        ),
        returnValue: _i3.Future<_i4.AudioFile?>.value(),
      ) as _i3.Future<_i4.AudioFile?>);

  @override
  List<_i4.AudioFile> getEpisodesByLanguage(
    List<_i4.AudioFile>? episodes,
    String? language,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguage,
          [
            episodes,
            language,
          ],
        ),
        returnValue: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> getEpisodesByCategory(
    List<_i4.AudioFile>? episodes,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByCategory,
          [
            episodes,
            category,
          ],
        ),
        returnValue: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> getEpisodesByLanguageAndCategory(
    List<_i4.AudioFile>? episodes,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguageAndCategory,
          [
            episodes,
            language,
            category,
          ],
        ),
        returnValue: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> filterEpisodesByQuery(
    List<_i4.AudioFile>? episodes,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterEpisodesByQuery,
          [
            episodes,
            query,
          ],
        ),
        returnValue: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  Map<String, dynamic> getEpisodeStatistics(List<_i4.AudioFile>? episodes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodeStatistics,
          [episodes],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
