name: from_fed_to_chain_audio
description: Audio player for From Fed to Chain TTS content

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Audio playback
  just_audio: ^0.9.36
  
  # File system access
  path: ^1.8.3
  
  # JSON handling (dart:convert is built-in)
  # No external package needed for JSON
  
  # HTTP for potential future API calls
  http: ^1.1.0
  dio: ^5.4.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # State management
  provider: ^6.1.1
  
  # UI enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Icons
  heroicons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - audio/
    - content/
    - .env
  
  # Fonts (if needed for custom typography)
  # fonts:
  #   - family: GeistSans
  #     fonts:
  #       - asset: fonts/GeistSans-Regular.ttf