// Mocks generated by Mockito 5.4.6 from annotations
// in from_fed_to_chain_app/test/services/audio_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i10;

import 'package:audio_service/audio_service.dart' as _i5;
import 'package:from_fed_to_chain_app/features/audio/services/background_audio_handler.dart'
    as _i3;
import 'package:from_fed_to_chain_app/features/content/models/audio_content.dart'
    as _i9;
import 'package:from_fed_to_chain_app/features/content/models/audio_file.dart'
    as _i4;
import 'package:from_fed_to_chain_app/features/content/services/content_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_1<T> extends _i1.SmartFake
    implements _i2.BehaviorSubject<T> {
  _FakeBehaviorSubject_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePublishSubject_2<T> extends _i1.SmartFake
    implements _i2.PublishSubject<T> {
  _FakePublishSubject_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_3<T> extends _i1.SmartFake
    implements _i2.ValueStream<T> {
  _FakeValueStream_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackgroundAudioHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundAudioHandler extends _i1.Mock
    implements _i3.BackgroundAudioHandler {
  @override
  Duration get duration => (super.noSuchMethod(
        Invocation.getter(#duration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#duration),
        ),
        returnValueForMissingStub: _FakeDuration_0(
          this,
          Invocation.getter(#duration),
        ),
      ) as Duration);

  @override
  set onSkipToNextEpisode(
          dynamic Function(_i4.AudioFile)? _onSkipToNextEpisode) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSkipToNextEpisode,
          _onSkipToNextEpisode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set onSkipToPreviousEpisode(
          dynamic Function(_i4.AudioFile)? _onSkipToPreviousEpisode) =>
      super.noSuchMethod(
        Invocation.setter(
          #onSkipToPreviousEpisode,
          _onSkipToPreviousEpisode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BehaviorSubject<_i5.PlaybackState> get playbackState =>
      (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _FakeBehaviorSubject_1<_i5.PlaybackState>(
          this,
          Invocation.getter(#playbackState),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<_i5.PlaybackState>(
          this,
          Invocation.getter(#playbackState),
        ),
      ) as _i2.BehaviorSubject<_i5.PlaybackState>);

  @override
  _i2.BehaviorSubject<List<_i5.MediaItem>> get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeBehaviorSubject_1<List<_i5.MediaItem>>(
          this,
          Invocation.getter(#queue),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<List<_i5.MediaItem>>(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i2.BehaviorSubject<List<_i5.MediaItem>>);

  @override
  _i2.BehaviorSubject<String> get queueTitle => (super.noSuchMethod(
        Invocation.getter(#queueTitle),
        returnValue: _FakeBehaviorSubject_1<String>(
          this,
          Invocation.getter(#queueTitle),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<String>(
          this,
          Invocation.getter(#queueTitle),
        ),
      ) as _i2.BehaviorSubject<String>);

  @override
  _i2.BehaviorSubject<_i5.MediaItem?> get mediaItem => (super.noSuchMethod(
        Invocation.getter(#mediaItem),
        returnValue: _FakeBehaviorSubject_1<_i5.MediaItem?>(
          this,
          Invocation.getter(#mediaItem),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<_i5.MediaItem?>(
          this,
          Invocation.getter(#mediaItem),
        ),
      ) as _i2.BehaviorSubject<_i5.MediaItem?>);

  @override
  _i2.BehaviorSubject<_i5.AndroidPlaybackInfo> get androidPlaybackInfo =>
      (super.noSuchMethod(
        Invocation.getter(#androidPlaybackInfo),
        returnValue: _FakeBehaviorSubject_1<_i5.AndroidPlaybackInfo>(
          this,
          Invocation.getter(#androidPlaybackInfo),
        ),
        returnValueForMissingStub:
            _FakeBehaviorSubject_1<_i5.AndroidPlaybackInfo>(
          this,
          Invocation.getter(#androidPlaybackInfo),
        ),
      ) as _i2.BehaviorSubject<_i5.AndroidPlaybackInfo>);

  @override
  _i2.BehaviorSubject<_i5.RatingStyle> get ratingStyle => (super.noSuchMethod(
        Invocation.getter(#ratingStyle),
        returnValue: _FakeBehaviorSubject_1<_i5.RatingStyle>(
          this,
          Invocation.getter(#ratingStyle),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<_i5.RatingStyle>(
          this,
          Invocation.getter(#ratingStyle),
        ),
      ) as _i2.BehaviorSubject<_i5.RatingStyle>);

  @override
  _i2.PublishSubject<dynamic> get customEvent => (super.noSuchMethod(
        Invocation.getter(#customEvent),
        returnValue: _FakePublishSubject_2<dynamic>(
          this,
          Invocation.getter(#customEvent),
        ),
        returnValueForMissingStub: _FakePublishSubject_2<dynamic>(
          this,
          Invocation.getter(#customEvent),
        ),
      ) as _i2.PublishSubject<dynamic>);

  @override
  _i2.BehaviorSubject<dynamic> get customState => (super.noSuchMethod(
        Invocation.getter(#customState),
        returnValue: _FakeBehaviorSubject_1<dynamic>(
          this,
          Invocation.getter(#customState),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_1<dynamic>(
          this,
          Invocation.getter(#customState),
        ),
      ) as _i2.BehaviorSubject<dynamic>);

  @override
  void setEpisodeNavigationCallbacks({
    required dynamic Function(_i4.AudioFile)? onNext,
    required dynamic Function(_i4.AudioFile)? onPrevious,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setEpisodeNavigationCallbacks,
          [],
          {
            #onNext: onNext,
            #onPrevious: onPrevious,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setAudioSource(
    String? url, {
    required String? title,
    String? artist,
    Duration? initialPosition,
    _i4.AudioFile? audioFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [url],
          {
            #title: title,
            #artist: artist,
            #initialPosition: initialPosition,
            #audioFile: audioFile,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> skipToNext() => (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> skipToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> fastForward() => (super.noSuchMethod(
        Invocation.method(
          #fastForward,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> rewind() => (super.noSuchMethod(
        Invocation.method(
          #rewind,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<dynamic> customAction(
    String? name, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customAction,
          [
            name,
            extras,
          ],
        ),
        returnValue: _i6.Future<dynamic>.value(),
        returnValueForMissingStub: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<void> testMediaSession() => (super.noSuchMethod(
        Invocation.method(
          #testMediaSession,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> onTaskRemoved() => (super.noSuchMethod(
        Invocation.method(
          #onTaskRemoved,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> prepare() => (super.noSuchMethod(
        Invocation.method(
          #prepare,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> prepareFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playFromMediaId(
    String? mediaId, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromMediaId,
          [
            mediaId,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playFromSearch(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromSearch,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playFromUri(
    Uri? uri, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #playFromUri,
          [
            uri,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> playMediaItem(_i5.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #playMediaItem,
          [mediaItem],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> click([_i5.MediaButton? button = _i5.MediaButton.media]) =>
      (super.noSuchMethod(
        Invocation.method(
          #click,
          [button],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addQueueItem(_i5.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItem,
          [mediaItem],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addQueueItems(List<_i5.MediaItem>? mediaItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #addQueueItems,
          [mediaItems],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertQueueItem(
    int? index,
    _i5.MediaItem? mediaItem,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertQueueItem,
          [
            index,
            mediaItem,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateQueue(List<_i5.MediaItem>? queue) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQueue,
          [queue],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateMediaItem(_i5.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMediaItem,
          [mediaItem],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeQueueItem(_i5.MediaItem? mediaItem) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeQueueItem,
          [mediaItem],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeQueueItemAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeQueueItemAt,
          [index],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> skipToQueueItem(int? index) => (super.noSuchMethod(
        Invocation.method(
          #skipToQueueItem,
          [index],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setRating(
    _i5.Rating? rating, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRating,
          [
            rating,
            extras,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setCaptioningEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setCaptioningEnabled,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setRepeatMode(_i5.AudioServiceRepeatMode? repeatMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRepeatMode,
          [repeatMode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setShuffleMode(_i5.AudioServiceShuffleMode? shuffleMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setShuffleMode,
          [shuffleMode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seekBackward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [begin],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> seekForward(bool? begin) => (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [begin],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> onNotificationDeleted() => (super.noSuchMethod(
        Invocation.method(
          #onNotificationDeleted,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i5.MediaItem>> getChildren(
    String? parentMediaId, [
    Map<String, dynamic>? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChildren,
          [
            parentMediaId,
            options,
          ],
        ),
        returnValue: _i6.Future<List<_i5.MediaItem>>.value(<_i5.MediaItem>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.MediaItem>>.value(<_i5.MediaItem>[]),
      ) as _i6.Future<List<_i5.MediaItem>>);

  @override
  _i2.ValueStream<Map<String, dynamic>> subscribeToChildren(
          String? parentMediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToChildren,
          [parentMediaId],
        ),
        returnValue: _FakeValueStream_3<Map<String, dynamic>>(
          this,
          Invocation.method(
            #subscribeToChildren,
            [parentMediaId],
          ),
        ),
        returnValueForMissingStub: _FakeValueStream_3<Map<String, dynamic>>(
          this,
          Invocation.method(
            #subscribeToChildren,
            [parentMediaId],
          ),
        ),
      ) as _i2.ValueStream<Map<String, dynamic>>);

  @override
  _i6.Future<_i5.MediaItem?> getMediaItem(String? mediaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaItem,
          [mediaId],
        ),
        returnValue: _i6.Future<_i5.MediaItem?>.value(),
        returnValueForMissingStub: _i6.Future<_i5.MediaItem?>.value(),
      ) as _i6.Future<_i5.MediaItem?>);

  @override
  _i6.Future<List<_i5.MediaItem>> search(
    String? query, [
    Map<String, dynamic>? extras,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            query,
            extras,
          ],
        ),
        returnValue: _i6.Future<List<_i5.MediaItem>>.value(<_i5.MediaItem>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i5.MediaItem>>.value(<_i5.MediaItem>[]),
      ) as _i6.Future<List<_i5.MediaItem>>);

  @override
  _i6.Future<void> androidAdjustRemoteVolume(
          _i5.AndroidVolumeDirection? direction) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidAdjustRemoteVolume,
          [direction],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> androidSetRemoteVolume(int? volumeIndex) =>
      (super.noSuchMethod(
        Invocation.method(
          #androidSetRemoteVolume,
          [volumeIndex],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentService extends _i1.Mock implements _i7.ContentService {
  @override
  List<_i4.AudioFile> get allEpisodes => (super.noSuchMethod(
        Invocation.getter(#allEpisodes),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> get filteredEpisodes => (super.noSuchMethod(
        Invocation.getter(#filteredEpisodes),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  String get selectedCategory => (super.noSuchMethod(
        Invocation.getter(#selectedCategory),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#selectedCategory),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#selectedCategory),
        ),
      ) as String);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  String get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sortOrder),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#sortOrder),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasEpisodes => (super.noSuchMethod(
        Invocation.getter(#hasEpisodes),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasFilteredResults => (super.noSuchMethod(
        Invocation.getter(#hasFilteredResults),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, DateTime> get listenHistory => (super.noSuchMethod(
        Invocation.getter(#listenHistory),
        returnValue: <String, DateTime>{},
        returnValueForMissingStub: <String, DateTime>{},
      ) as Map<String, DateTime>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.AudioFile> getListenHistoryEpisodes({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListenHistoryEpisodes,
          [],
          {#limit: limit},
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  bool isEpisodeFinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeFinished,
          [episodeId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool isEpisodeUnfinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeUnfinished,
          [episodeId],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> addToListenHistory(
    _i4.AudioFile? episode, {
    DateTime? at,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToListenHistory,
          [episode],
          {#at: at},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromListenHistory(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromListenHistory,
          [episodeId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearListenHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearListenHistory,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i9.AudioContent?> fetchContentById(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchContentById,
          [
            id,
            language,
            category,
          ],
        ),
        returnValue: _i6.Future<_i9.AudioContent?>.value(),
        returnValueForMissingStub: _i6.Future<_i9.AudioContent?>.value(),
      ) as _i6.Future<_i9.AudioContent?>);

  @override
  _i6.Future<_i9.AudioContent?> getContentForAudioFile(
          _i4.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentForAudioFile,
          [audioFile],
        ),
        returnValue: _i6.Future<_i9.AudioContent?>.value(),
        returnValueForMissingStub: _i6.Future<_i9.AudioContent?>.value(),
      ) as _i6.Future<_i9.AudioContent?>);

  @override
  _i6.Future<_i4.AudioFile?> getAudioFileById(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAudioFileById,
          [contentId],
        ),
        returnValue: _i6.Future<_i4.AudioFile?>.value(),
        returnValueForMissingStub: _i6.Future<_i4.AudioFile?>.value(),
      ) as _i6.Future<_i4.AudioFile?>);

  @override
  _i6.Future<void> prefetchContent(List<_i4.AudioFile>? audioFiles) =>
      (super.noSuchMethod(
        Invocation.method(
          #prefetchContent,
          [audioFiles],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clearContentCache() => super.noSuchMethod(
        Invocation.method(
          #clearContentCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> updateEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markEpisodeAsFinished(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEpisodeAsFinished,
          [episodeId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  double getEpisodeCompletion(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #getEpisodeCompletion,
          [episodeId],
        ),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  List<_i4.AudioFile> getUnfinishedEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getUnfinishedEpisodes,
          [],
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  _i6.Future<void> setSortOrder(String? sortOrder) => (super.noSuchMethod(
        Invocation.method(
          #setSortOrder,
          [sortOrder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadAllEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #loadAllEpisodes,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadEpisodesForLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEpisodesForLanguage,
          [language],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setCategory(String? category) => (super.noSuchMethod(
        Invocation.method(
          #setCategory,
          [category],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createPlaylistFromFiltered(String? name) => super.noSuchMethod(
        Invocation.method(
          #createPlaylistFromFiltered,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createPlaylist(
    String? name,
    List<_i4.AudioFile>? episodes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #createPlaylist,
          [
            name,
            episodes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addToCurrentPlaylist(_i4.AudioFile? episode) => super.noSuchMethod(
        Invocation.method(
          #addToCurrentPlaylist,
          [episode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCurrentPlaylist(_i4.AudioFile? episode) => super.noSuchMethod(
        Invocation.method(
          #removeFromCurrentPlaylist,
          [episode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCurrentPlaylist() => super.noSuchMethod(
        Invocation.method(
          #clearCurrentPlaylist,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.AudioFile> getEpisodesByLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguage,
          [language],
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> getEpisodesByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByCategory,
          [category],
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  List<_i4.AudioFile> getEpisodesByLanguageAndCategory(
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguageAndCategory,
          [
            language,
            category,
          ],
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i4.AudioFile>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEpisodes,
          [query],
        ),
        returnValue: _i6.Future<List<_i4.AudioFile>>.value(<_i4.AudioFile>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.AudioFile>>.value(<_i4.AudioFile>[]),
      ) as _i6.Future<List<_i4.AudioFile>>);

  @override
  Map<String, dynamic> getDebugInfo(_i4.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebugInfo,
          [audioFile],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i6.Future<void> setEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void cacheContent(
    String? id,
    String? language,
    String? category,
    _i9.AudioContent? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheContent,
          [
            id,
            language,
            category,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.AudioContent? getCachedContent(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedContent,
          [
            id,
            language,
            category,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i9.AudioContent?);

  @override
  List<_i4.AudioFile> getFilteredEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getFilteredEpisodes,
          [],
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  _i4.AudioFile? getNextEpisode(_i4.AudioFile? currentEpisode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNextEpisode,
          [currentEpisode],
        ),
        returnValueForMissingStub: null,
      ) as _i4.AudioFile?);

  @override
  _i4.AudioFile? getPreviousEpisode(_i4.AudioFile? currentEpisode) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreviousEpisode,
          [currentEpisode],
        ),
        returnValueForMissingStub: null,
      ) as _i4.AudioFile?);

  @override
  List<_i4.AudioFile> advancedSearch(
    List<_i4.AudioFile>? episodes, {
    String? query,
    List<String>? languages,
    List<String>? categories,
    DateTime? dateFrom,
    DateTime? dateTo,
    Duration? minDuration,
    Duration? maxDuration,
    String? sortOrder = 'newest',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #advancedSearch,
          [episodes],
          {
            #query: query,
            #languages: languages,
            #categories: categories,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #minDuration: minDuration,
            #maxDuration: maxDuration,
            #sortOrder: sortOrder,
          },
        ),
        returnValue: <_i4.AudioFile>[],
        returnValueForMissingStub: <_i4.AudioFile>[],
      ) as List<_i4.AudioFile>);

  @override
  void setEpisodesForTesting(List<_i4.AudioFile>? episodes) =>
      super.noSuchMethod(
        Invocation.method(
          #setEpisodesForTesting,
          [episodes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingForTesting(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoadingForTesting,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setErrorForTesting(String? error) => super.noSuchMethod(
        Invocation.method(
          #setErrorForTesting,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedLanguage(String? language) => super.noSuchMethod(
        Invocation.method(
          #setSelectedLanguage,
          [language],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedCategory(String? category) => super.noSuchMethod(
        Invocation.method(
          #setSelectedCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
