// Mocks generated by Mockito 5.4.6 from annotations
// in from_fed_to_chain_app/test/services/player_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:from_fed_to_chain_app/features/audio/services/player_adapter.dart'
    as _i2;
import 'package:from_fed_to_chain_app/features/audio/services/player_state_notifier.dart'
    as _i4;
import 'package:from_fed_to_chain_app/features/content/models/audio_file.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPlayerAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlayerAdapter extends _i1.Mock implements _i2.IPlayerAdapter {
  MockIPlayerAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.AppPlaybackState> get playbackStateStream =>
      (super.noSuchMethod(
        Invocation.getter(#playbackStateStream),
        returnValue: _i3.Stream<_i4.AppPlaybackState>.empty(),
      ) as _i3.Stream<_i4.AppPlaybackState>);

  @override
  _i3.Stream<Duration> get positionStream => (super.noSuchMethod(
        Invocation.getter(#positionStream),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);

  @override
  _i3.Stream<Duration?> get durationStream => (super.noSuchMethod(
        Invocation.getter(#durationStream),
        returnValue: _i3.Stream<Duration?>.empty(),
      ) as _i3.Stream<Duration?>);

  @override
  _i3.Stream<double> get speedStream => (super.noSuchMethod(
        Invocation.getter(#speedStream),
        returnValue: _i3.Stream<double>.empty(),
      ) as _i3.Stream<double>);

  @override
  _i4.AppPlaybackState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i4.AppPlaybackState.stopped,
      ) as _i4.AppPlaybackState);

  @override
  Duration get currentPosition => (super.noSuchMethod(
        Invocation.getter(#currentPosition),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#currentPosition),
        ),
      ) as Duration);

  @override
  double get currentSpeed => (super.noSuchMethod(
        Invocation.getter(#currentSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<void> setAudioSource(
    _i5.AudioFile? audioFile, {
    Duration? initialPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioSource,
          [audioFile],
          {#initialPosition: initialPosition},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> play() => (super.noSuchMethod(
        Invocation.method(
          #play,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setSpeed,
          [speed],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipForward(
          [Duration? duration = const Duration(seconds: 30)]) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipForward,
          [duration],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> skipBackward(
          [Duration? duration = const Duration(seconds: 10)]) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipBackward,
          [duration],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PlayerStateNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerStateNotifier extends _i1.Mock
    implements _i4.PlayerStateNotifier {
  MockPlayerStateNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppPlaybackState get playbackState => (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _i4.AppPlaybackState.stopped,
      ) as _i4.AppPlaybackState);

  @override
  Duration get currentPosition => (super.noSuchMethod(
        Invocation.getter(#currentPosition),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#currentPosition),
        ),
      ) as Duration);

  @override
  Duration get totalDuration => (super.noSuchMethod(
        Invocation.getter(#totalDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#totalDuration),
        ),
      ) as Duration);

  @override
  double get playbackSpeed => (super.noSuchMethod(
        Invocation.getter(#playbackSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get isIdle => (super.noSuchMethod(
        Invocation.getter(#isIdle),
        returnValue: false,
      ) as bool);

  @override
  bool get isCompleted => (super.noSuchMethod(
        Invocation.getter(#isCompleted),
        returnValue: false,
      ) as bool);

  @override
  double get progress => (super.noSuchMethod(
        Invocation.getter(#progress),
        returnValue: 0.0,
      ) as double);

  @override
  String get formattedCurrentPosition => (super.noSuchMethod(
        Invocation.getter(#formattedCurrentPosition),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#formattedCurrentPosition),
        ),
      ) as String);

  @override
  String get formattedTotalDuration => (super.noSuchMethod(
        Invocation.getter(#formattedTotalDuration),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#formattedTotalDuration),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateState(_i4.AppPlaybackState? state) => super.noSuchMethod(
        Invocation.method(
          #updateState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePosition(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #updatePosition,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateDuration(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #updateDuration,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #updateSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setError(String? error) => super.noSuchMethod(
        Invocation.method(
          #setError,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPlaybackCompleted() => super.noSuchMethod(
        Invocation.method(
          #onPlaybackCompleted,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPlaybackStateForTesting(_i4.AppPlaybackState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaybackStateForTesting,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPositionForTesting(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #setPositionForTesting,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDurationForTesting(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #setDurationForTesting,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSpeedForTesting(double? speed) => super.noSuchMethod(
        Invocation.method(
          #setSpeedForTesting,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setErrorForTesting(String? error) => super.noSuchMethod(
        Invocation.method(
          #setErrorForTesting,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearErrorForTesting() => super.noSuchMethod(
        Invocation.method(
          #clearErrorForTesting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
