name: from_fed_to_chain_app
description: Modern Flutter audio streaming app for From Fed to Chain crypto/macro economics content

publish_to: "none"

version: 1.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Audio playback and background support
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.18

  # HTTP client for API calls
  http: ^1.1.0
  dio: ^5.4.0

  # Environment configuration
  flutter_dotenv: ^5.1.0

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.2.2

  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # UI enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Icons and design
  heroicons: ^0.9.0

  # Sharing and deep linking
  share_plus: ^7.2.2
  app_links: ^6.3.2

  # Utils
  path: ^1.8.3
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  coverage: ^1.6.3
  yaml: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.28.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - .env

  # Custom fonts (optional)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true # Remove alpha channel for iOS icons
