name: from_fed_to_chain_app
description: Modern Flutter audio streaming app for From Fed to Chain crypto/macro economics content

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Audio playback and background support
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.18

  # HTTP client for API calls
  http: ^1.1.0
  dio: ^5.4.0

  # Environment configuration
  flutter_dotenv: ^5.1.0

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.2.2

  # UI enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Icons and design
  heroicons: ^0.9.0

  # Utils
  path: ^1.8.3
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  coverage: ^1.6.3
  yaml: ^3.1.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - .env

  # Custom fonts (optional)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Inter-SemiBold.ttf
  #         weight: 600