// Mocks generated by Mockito 5.4.6 from annotations
// in from_fed_to_chain_app/test/features/content/widgets/content_display_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:from_fed_to_chain_app/features/content/models/audio_content.dart'
    as _i6;
import 'package:from_fed_to_chain_app/features/content/models/audio_file.dart'
    as _i3;
import 'package:from_fed_to_chain_app/features/content/services/content_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentService extends _i1.Mock implements _i2.ContentService {
  MockContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AudioFile> get allEpisodes => (super.noSuchMethod(
        Invocation.getter(#allEpisodes),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> get filteredEpisodes => (super.noSuchMethod(
        Invocation.getter(#filteredEpisodes),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  String get selectedCategory => (super.noSuchMethod(
        Invocation.getter(#selectedCategory),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#selectedCategory),
        ),
      ) as String);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  String get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#sortOrder),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get hasEpisodes => (super.noSuchMethod(
        Invocation.getter(#hasEpisodes),
        returnValue: false,
      ) as bool);

  @override
  bool get hasFilteredResults => (super.noSuchMethod(
        Invocation.getter(#hasFilteredResults),
        returnValue: false,
      ) as bool);

  @override
  Map<String, DateTime> get listenHistory => (super.noSuchMethod(
        Invocation.getter(#listenHistory),
        returnValue: <String, DateTime>{},
      ) as Map<String, DateTime>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.AudioFile> getListenHistoryEpisodes({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListenHistoryEpisodes,
          [],
          {#limit: limit},
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  bool isEpisodeFinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeFinished,
          [episodeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isEpisodeUnfinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeUnfinished,
          [episodeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> addToListenHistory(
    _i3.AudioFile? episode, {
    DateTime? at,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToListenHistory,
          [episode],
          {#at: at},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromListenHistory(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromListenHistory,
          [episodeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearListenHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearListenHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.AudioContent?> fetchContentById(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchContentById,
          [
            id,
            language,
            category,
          ],
        ),
        returnValue: _i5.Future<_i6.AudioContent?>.value(),
      ) as _i5.Future<_i6.AudioContent?>);

  @override
  _i5.Future<_i6.AudioContent?> getContentForAudioFile(
          _i3.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentForAudioFile,
          [audioFile],
        ),
        returnValue: _i5.Future<_i6.AudioContent?>.value(),
      ) as _i5.Future<_i6.AudioContent?>);

  @override
  _i5.Future<_i3.AudioFile?> getAudioFileById(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAudioFileById,
          [contentId],
        ),
        returnValue: _i5.Future<_i3.AudioFile?>.value(),
      ) as _i5.Future<_i3.AudioFile?>);

  @override
  _i5.Future<void> prefetchContent(List<_i3.AudioFile>? audioFiles) =>
      (super.noSuchMethod(
        Invocation.method(
          #prefetchContent,
          [audioFiles],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearContentCache() => super.noSuchMethod(
        Invocation.method(
          #clearContentCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markEpisodeAsFinished(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEpisodeAsFinished,
          [episodeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  double getEpisodeCompletion(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #getEpisodeCompletion,
          [episodeId],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i3.AudioFile> getUnfinishedEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getUnfinishedEpisodes,
          [],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  _i5.Future<void> setSortOrder(String? sortOrder) => (super.noSuchMethod(
        Invocation.method(
          #setSortOrder,
          [sortOrder],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadAllEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #loadAllEpisodes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadEpisodesForLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEpisodesForLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCategory(String? category) => (super.noSuchMethod(
        Invocation.method(
          #setCategory,
          [category],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.AudioFile> getEpisodesByLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguage,
          [language],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> getEpisodesByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByCategory,
          [category],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> getEpisodesByLanguageAndCategory(
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguageAndCategory,
          [
            language,
            category,
          ],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i3.AudioFile>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEpisodes,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.AudioFile>>.value(<_i3.AudioFile>[]),
      ) as _i5.Future<List<_i3.AudioFile>>);

  @override
  Map<String, dynamic> getDebugInfo(_i3.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebugInfo,
          [audioFile],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> setEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void cacheContent(
    String? id,
    String? language,
    String? category,
    _i6.AudioContent? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheContent,
          [
            id,
            language,
            category,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.AudioContent? getCachedContent(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedContent,
        [
          id,
          language,
          category,
        ],
      )) as _i6.AudioContent?);

  @override
  List<_i3.AudioFile> getFilteredEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getFilteredEpisodes,
          [],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> advancedSearch(
    List<_i3.AudioFile>? episodes, {
    String? query,
    List<String>? languages,
    List<String>? categories,
    DateTime? dateFrom,
    DateTime? dateTo,
    Duration? minDuration,
    Duration? maxDuration,
    String? sortOrder = 'newest',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #advancedSearch,
          [episodes],
          {
            #query: query,
            #languages: languages,
            #categories: categories,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #minDuration: minDuration,
            #maxDuration: maxDuration,
            #sortOrder: sortOrder,
          },
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  void setEpisodesForTesting(List<_i3.AudioFile>? episodes) =>
      super.noSuchMethod(
        Invocation.method(
          #setEpisodesForTesting,
          [episodes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingForTesting(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoadingForTesting,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setErrorForTesting(String? error) => super.noSuchMethod(
        Invocation.method(
          #setErrorForTesting,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedLanguage(String? language) => super.noSuchMethod(
        Invocation.method(
          #setSelectedLanguage,
          [language],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedCategory(String? category) => super.noSuchMethod(
        Invocation.method(
          #setSelectedCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
