// Mocks generated by Mockito 5.4.6 from annotations
// in from_fed_to_chain_app/test/widgets/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:from_fed_to_chain_app/models/audio_content.dart' as _i6;
import 'package:from_fed_to_chain_app/models/audio_file.dart' as _i3;
import 'package:from_fed_to_chain_app/services/audio_service.dart' as _i8;
import 'package:from_fed_to_chain_app/services/auth/auth_service.dart' as _i9;
import 'package:from_fed_to_chain_app/services/content_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ContentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentService extends _i1.Mock implements _i2.ContentService {
  MockContentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AudioFile> get allEpisodes => (super.noSuchMethod(
        Invocation.getter(#allEpisodes),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> get filteredEpisodes => (super.noSuchMethod(
        Invocation.getter(#filteredEpisodes),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  String get selectedLanguage => (super.noSuchMethod(
        Invocation.getter(#selectedLanguage),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#selectedLanguage),
        ),
      ) as String);

  @override
  String get selectedCategory => (super.noSuchMethod(
        Invocation.getter(#selectedCategory),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#selectedCategory),
        ),
      ) as String);

  @override
  String get searchQuery => (super.noSuchMethod(
        Invocation.getter(#searchQuery),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#searchQuery),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  String get sortOrder => (super.noSuchMethod(
        Invocation.getter(#sortOrder),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#sortOrder),
        ),
      ) as String);

  @override
  Map<String, DateTime> get listenHistory => (super.noSuchMethod(
        Invocation.getter(#listenHistory),
        returnValue: <String, DateTime>{},
      ) as Map<String, DateTime>);

  @override
  bool get hasEpisodes => (super.noSuchMethod(
        Invocation.getter(#hasEpisodes),
        returnValue: false,
      ) as bool);

  @override
  bool get hasFilteredResults => (super.noSuchMethod(
        Invocation.getter(#hasFilteredResults),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.AudioFile> getListenHistoryEpisodes({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListenHistoryEpisodes,
          [],
          {#limit: limit},
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  double getEpisodeCompletion(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #getEpisodeCompletion,
          [episodeId],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  bool isEpisodeFinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeFinished,
          [episodeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool isEpisodeUnfinished(String? episodeId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeUnfinished,
          [episodeId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> addToListenHistory(
    _i3.AudioFile? episode, {
    DateTime? at,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToListenHistory,
          [episode],
          {#at: at},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeFromListenHistory(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromListenHistory,
          [episodeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearListenHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearListenHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.AudioContent?> fetchContentById(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchContentById,
          [
            id,
            language,
            category,
          ],
        ),
        returnValue: _i5.Future<_i6.AudioContent?>.value(),
      ) as _i5.Future<_i6.AudioContent?>);

  @override
  _i5.Future<_i6.AudioContent?> getContentForAudioFile(
          _i3.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getContentForAudioFile,
          [audioFile],
        ),
        returnValue: _i5.Future<_i6.AudioContent?>.value(),
      ) as _i5.Future<_i6.AudioContent?>);

  @override
  _i6.AudioContent? getCachedContent(
    String? id,
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedContent,
        [
          id,
          language,
          category,
        ],
      )) as _i6.AudioContent?);

  @override
  _i5.Future<_i3.AudioFile?> getAudioFileById(String? contentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAudioFileById,
          [contentId],
        ),
        returnValue: _i5.Future<_i3.AudioFile?>.value(),
      ) as _i5.Future<_i3.AudioFile?>);

  @override
  _i5.Future<void> prefetchContent(List<_i3.AudioFile>? audioFiles) =>
      (super.noSuchMethod(
        Invocation.method(
          #prefetchContent,
          [audioFiles],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearContentCache() => super.noSuchMethod(
        Invocation.method(
          #clearContentCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> updateEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markEpisodeAsFinished(String? episodeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markEpisodeAsFinished,
          [episodeId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i3.AudioFile> getUnfinishedEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getUnfinishedEpisodes,
          [],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  _i5.Future<void> setSortOrder(String? sortOrder) => (super.noSuchMethod(
        Invocation.method(
          #setSortOrder,
          [sortOrder],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadAllEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #loadAllEpisodes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadEpisodesForLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEpisodesForLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setLanguage(String? language) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [language],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setCategory(String? category) => (super.noSuchMethod(
        Invocation.method(
          #setCategory,
          [category],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
        Invocation.method(
          #setSearchQuery,
          [query],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createPlaylistFromFiltered(String? name) => super.noSuchMethod(
        Invocation.method(
          #createPlaylistFromFiltered,
          [name],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createPlaylist(
    String? name,
    List<_i3.AudioFile>? episodes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #createPlaylist,
          [
            name,
            episodes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addToCurrentPlaylist(_i3.AudioFile? episode) => super.noSuchMethod(
        Invocation.method(
          #addToCurrentPlaylist,
          [episode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCurrentPlaylist(_i3.AudioFile? episode) => super.noSuchMethod(
        Invocation.method(
          #removeFromCurrentPlaylist,
          [episode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AudioFile? getNextEpisode(_i3.AudioFile? currentEpisode) =>
      (super.noSuchMethod(Invocation.method(
        #getNextEpisode,
        [currentEpisode],
      )) as _i3.AudioFile?);

  @override
  _i3.AudioFile? getPreviousEpisode(_i3.AudioFile? currentEpisode) =>
      (super.noSuchMethod(Invocation.method(
        #getPreviousEpisode,
        [currentEpisode],
      )) as _i3.AudioFile?);

  @override
  List<_i3.AudioFile> getEpisodesByLanguage(String? language) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguage,
          [language],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> getEpisodesByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByCategory,
          [category],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  List<_i3.AudioFile> getEpisodesByLanguageAndCategory(
    String? language,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByLanguageAndCategory,
          [
            language,
            category,
          ],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  Map<String, dynamic> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<_i3.AudioFile>> searchEpisodes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEpisodes,
          [query],
        ),
        returnValue: _i5.Future<List<_i3.AudioFile>>.value(<_i3.AudioFile>[]),
      ) as _i5.Future<List<_i3.AudioFile>>);

  @override
  Map<String, dynamic> getDebugInfo(_i3.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDebugInfo,
          [audioFile],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> setEpisodeCompletion(
    String? episodeId,
    double? completion,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEpisodeCompletion,
          [
            episodeId,
            completion,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void clearCurrentPlaylist() => super.noSuchMethod(
        Invocation.method(
          #clearCurrentPlaylist,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cacheContent(
    String? id,
    String? language,
    String? category,
    _i6.AudioContent? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheContent,
          [
            id,
            language,
            category,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.AudioFile> getFilteredEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getFilteredEpisodes,
          [],
        ),
        returnValue: <_i3.AudioFile>[],
      ) as List<_i3.AudioFile>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEpisodesForTesting(List<_i3.AudioFile>? episodes) =>
      super.noSuchMethod(
        Invocation.method(
          #setEpisodesForTesting,
          [episodes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoadingForTesting(bool? loading) => super.noSuchMethod(
        Invocation.method(
          #setLoadingForTesting,
          [loading],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setErrorForTesting(String? error) => super.noSuchMethod(
        Invocation.method(
          #setErrorForTesting,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedLanguage(String? language) => super.noSuchMethod(
        Invocation.method(
          #setSelectedLanguage,
          [language],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSelectedCategory(String? category) => super.noSuchMethod(
        Invocation.method(
          #setSelectedCategory,
          [category],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioService extends _i1.Mock implements _i8.AudioService {
  MockAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.PlaybackState get playbackState => (super.noSuchMethod(
        Invocation.getter(#playbackState),
        returnValue: _i8.PlaybackState.stopped,
      ) as _i8.PlaybackState);

  @override
  Duration get currentPosition => (super.noSuchMethod(
        Invocation.getter(#currentPosition),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#currentPosition),
        ),
      ) as Duration);

  @override
  Duration get totalDuration => (super.noSuchMethod(
        Invocation.getter(#totalDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#totalDuration),
        ),
      ) as Duration);

  @override
  double get playbackSpeed => (super.noSuchMethod(
        Invocation.getter(#playbackSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  bool get autoplayEnabled => (super.noSuchMethod(
        Invocation.getter(#autoplayEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get repeatEnabled => (super.noSuchMethod(
        Invocation.getter(#repeatEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  bool get isPaused => (super.noSuchMethod(
        Invocation.getter(#isPaused),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get isIdle => (super.noSuchMethod(
        Invocation.getter(#isIdle),
        returnValue: false,
      ) as bool);

  @override
  double get progress => (super.noSuchMethod(
        Invocation.getter(#progress),
        returnValue: 0.0,
      ) as double);

  @override
  String get formattedCurrentPosition => (super.noSuchMethod(
        Invocation.getter(#formattedCurrentPosition),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#formattedCurrentPosition),
        ),
      ) as String);

  @override
  String get formattedTotalDuration => (super.noSuchMethod(
        Invocation.getter(#formattedTotalDuration),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#formattedTotalDuration),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> playAudio(_i3.AudioFile? audioFile) => (super.noSuchMethod(
        Invocation.method(
          #playAudio,
          [audioFile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void setAutoplayEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setAutoplayEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRepeatEnabled(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #setRepeatEnabled,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> togglePlayPause() => (super.noSuchMethod(
        Invocation.method(
          #togglePlayPause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToNextEpisode() => (super.noSuchMethod(
        Invocation.method(
          #skipToNextEpisode,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToPreviousEpisode() => (super.noSuchMethod(
        Invocation.method(
          #skipToPreviousEpisode,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekTo(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seekTo,
          [position],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipForward() => (super.noSuchMethod(
        Invocation.method(
          #skipForward,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipBackward() => (super.noSuchMethod(
        Invocation.method(
          #skipBackward,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPlaybackSpeed(double? speed) => (super.noSuchMethod(
        Invocation.method(
          #setPlaybackSpeed,
          [speed],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> testMediaSession() => (super.noSuchMethod(
        Invocation.method(
          #testMediaSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToNext() => (super.noSuchMethod(
        Invocation.method(
          #skipToNext,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> skipToPrevious() => (super.noSuchMethod(
        Invocation.method(
          #skipToPrevious,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekForward() => (super.noSuchMethod(
        Invocation.method(
          #seekForward,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> seekBackward() => (super.noSuchMethod(
        Invocation.method(
          #seekBackward,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> play(_i3.AudioFile? audioFile) => (super.noSuchMethod(
        Invocation.method(
          #play,
          [audioFile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void toggleAutoplay() => super.noSuchMethod(
        Invocation.method(
          #toggleAutoplay,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleRepeat() => super.noSuchMethod(
        Invocation.method(
          #toggleRepeat,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableAutoplay(bool? enabled) => super.noSuchMethod(
        Invocation.method(
          #enableAutoplay,
          [enabled],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> onEpisodeCompleted() => (super.noSuchMethod(
        Invocation.method(
          #onEpisodeCompleted,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateProgress(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #updateProgress,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handlePlaybackError(String? message) => super.noSuchMethod(
        Invocation.method(
          #handlePlaybackError,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleNetworkTimeout() => super.noSuchMethod(
        Invocation.method(
          #handleNetworkTimeout,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleInvalidUrl(_i3.AudioFile? audioFile) => super.noSuchMethod(
        Invocation.method(
          #handleInvalidUrl,
          [audioFile],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isValidAudioFile(_i3.AudioFile? audioFile) => (super.noSuchMethod(
        Invocation.method(
          #isValidAudioFile,
          [audioFile],
        ),
        returnValue: false,
      ) as bool);

  @override
  void savePlaybackState() => super.noSuchMethod(
        Invocation.method(
          #savePlaybackState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> restorePlaybackPosition(_i3.AudioFile? audioFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #restorePlaybackPosition,
          [audioFile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPlaybackStateForTesting(_i8.PlaybackState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #setPlaybackStateForTesting,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCurrentAudioFileForTesting(_i3.AudioFile? audioFile) =>
      super.noSuchMethod(
        Invocation.method(
          #setCurrentAudioFileForTesting,
          [audioFile],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setDurationForTesting(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #setDurationForTesting,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPositionForTesting(Duration? position) => super.noSuchMethod(
        Invocation.method(
          #setPositionForTesting,
          [position],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setErrorForTesting(String? error) => super.noSuchMethod(
        Invocation.method(
          #setErrorForTesting,
          [error],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearErrorForTesting() => super.noSuchMethod(
        Invocation.method(
          #clearErrorForTesting,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthState get authState => (super.noSuchMethod(
        Invocation.getter(#authState),
        returnValue: _i9.AuthState.initial,
      ) as _i9.AuthState);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateProfile({
    String? name,
    String? photoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #name: name,
            #photoUrl: photoUrl,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
